# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ iwyu ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    #- name: Download artifact
    #  uses: dawidd6/action-download-artifact@master
    #  with:
    #    github_token: ${{secrets.GITHUB_TOKEN}}
    #    owner: OpenMS
    #    repo: contrib
    #    commit: f6d6774a8beec5014702f31763f058ff2d59c242
    #    workflow: main.yml
    #    name: contrib-build-${{ runner.os }}
    #    path: contrib_build
        
    - name: Load contrib build
      run: |
          mkdir contribbld
          cd contribbld
          curl -o contribbld.tar.gz https://abibuilder.informatik.uni-tuebingen.de/archive/openms/contrib/linux/debian/ubuntu/18.04/x64/g%2B%2B-7/contrib_build.tar.gz
          tar -xzf contribbld.tar.gz
          rm contribbld.tar.gz
    
    - name: Install Qt
      run: sudo apt-get install -y qtbase5-dev
    
    - name: configure
      run: |
          mkdir build && cd build
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DWITH_GUI=OFF -DOPENMS_CONTRIB_LIBS=${GITHUB_WORKSPACE}/contribbld ../

    - name: Run Include What You Use
      uses: EmilGedda/include-what-you-use-action@v1.0
      with:
         compilation-database-path: './build/'
         output-format: 'iwyu' # Or 'clang'
         no-error: 'false'
